name: guaruba
description: "Um programa para ensinar logica de programação básica"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc_provider: ^1.0.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  collection: ^1.15.0
  shared_preferences: ^2.3.3
  tutorial_coach_mark: ^1.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon_background.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/juba.svg
    - assets/icon/icon.png
    - assets/icon/icon_foreground.png
    - assets/icon/icon_background.png





